sudo: required
dist: trusty
language: cpp
compiler: g++

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

 install:
  - sudo apt-get -y install qt55[QTPACKAGE]
  - sudo apt-get install -qq g++-4.8

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - export CXX="g++-4.8"
  - make
  