sudo: required
dist: trusty
language: cpp
compiler: 
    - gcc
    - clang

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt58[QTPACKAGE]
  - sudo apt-get -y install qt58websockets

script:
  - source /opt/qt58/bin/qt58-env.sh
  - if [ "$CXX" == "g++" ]; then /opt/qt58/bin/qmake; fi
  - if [ "$CXX" == "clang++" ]; then /opt/qt58/bin/qmake -spec linux-clang; fi
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    
notifications:
  slack: twicecast-eip:fzwNN3MrxGQ7v6Bza2Bx9apE#travis