sudo: required
dist: trusty
language: cpp
compiler: 
    - gcc
    - clang

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt55[QTPACKAGE]
  - if [ \"$CXX\" = \"g++\" ]; then export CXX=\"g++-4.8\" CC=\"gcc-4.8\"; fi

script:
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang